//! Query and validate the OpenPhysics problem registry. See docs/DESIGN.md.

mod problem;

use clap::{Parser, Subcommand};
use problem::{Field, Kind, Problem, Status, Tag};
use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::exit;

#[derive(Parser)]
#[command(version, about)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// List entries: id, field, name
    List {
        #[arg(long, ignore_case = true)]
        field: Option<Field>,
        #[arg(long)]
        status: Option<Status>,
        #[arg(long)]
        kind: Option<Kind>,
    },
    /// Print an entry, or one of its tags
    Show { id: u32, tag: Option<Tag> },
    /// Ids whose keys, name, or claim contain the term
    Grep { term: String },
    /// Validate every entry against docs/DESIGN.md
    Check,
    /// Next unused id
    Next,
    /// Regenerate problems/README.md
    Index,
}

/// The nearest ancestor of the working directory that contains `problems/`.
fn problems_dir() -> PathBuf {
    let cwd = env::current_dir().unwrap();
    cwd.ancestors()
        .map(|d| d.join("problems"))
        .find(|p| p.is_dir())
        .unwrap_or_else(|| {
            eprintln!("no problems/ directory in {} or its parents", cwd.display());
            exit(2)
        })
}

fn main() {
    let cli = Cli::parse();
    let problems = problems_dir();
    let (entries, issues) = problem::load(&problems);

    match cli.command {
        Command::Check => {
            for issue in &issues {
                println!("{issue}");
            }
            if issues.is_empty() {
                println!("{} entries valid", entries.len());
            } else {
                exit(1)
            }
        }
        Command::List { field, status, kind } => {
            for p in entries.iter().filter(|p| {
                field.is_none_or(|f| p.field == f)
                    && status.is_none_or(|s| p.status == s)
                    && kind.is_none_or(|k| p.kind == k)
            }) {
                println!("{}\t{}\t{}", p.id, p.field, p.name);
            }
        }
        Command::Show { id, tag } => {
            let p = find(&entries, id);
            match tag {
                Some(tag) => println!("{}", p.tag(tag)),
                None => print!("{}", fs::read_to_string(&p.path).unwrap()),
            }
        }
        Command::Grep { term } => {
            let term = term.to_lowercase();
            for p in entries.iter().filter(|p| {
                [&p.keys, &p.name, &p.claim].iter().any(|s| s.to_lowercase().contains(&term))
            }) {
                println!("{}\t{}\t{}", p.id, p.field, p.name);
            }
        }
        Command::Next => println!("{}", entries.last().map_or(1, |p| p.id + 1)),
        Command::Index => {
            let mut out = String::from(
                "# Problems\n\nGenerated by `openphysics-cli index`. Do not edit by hand.\n\n\
                 | id | kind | field | name | status |\n|---|---|---|---|---|\n",
            );
            for p in &entries {
                out += &format!("| [{0}]({0}/PROBLEM.md) | {1} | {2} | {3} | {4} |\n", p.id, p.kind, p.field, p.name, p.status);
            }
            fs::write(problems.join("README.md"), out).unwrap();
        }
    }
}

fn find(entries: &[Problem], id: u32) -> &Problem {
    entries.iter().find(|p| p.id == id).unwrap_or_else(|| {
        eprintln!("no entry {id}");
        exit(2)
    })
}
